// Pulls the two typefaces into the repo so the app looks right with no signal.
//
//   node tools/vendor-fonts.mjs
//
// Why this exists: the service worker deliberately ignores cross-origin
// requests (so it can never interfere with Firestore), which means the Google
// Fonts stylesheet and its woff2 files were the one thing the app could not
// cache. Offline, Archivo and IBM Plex Mono fell back to Helvetica and the
// system mono — legible, but the Braun two-face split is half the design, and
// this is an app whose whole premise is the Mojave.
//
// Only the LATIN subset is taken. The full set is five subsets per weight and
// the trip does not need Vietnamese.
//
// Licensing: both families are SIL Open Font License 1.1, which permits
// redistribution, including in a public repo. fonts/OFL.txt records that.

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = resolve(ROOT, 'fonts');
const API = 'https://fonts.googleapis.com/css2?family=Archivo:wght@400;500&family=IBM+Plex+Mono:wght@400;500&display=swap';

// Google serves woff2 only to browsers that say they can take it.
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
           '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const css = await (await fetch(API, { headers: { 'User-Agent': UA } })).text();

// Split on the subset comments Google emits and keep only /* latin */.
const faces = [];
for (const block of css.split('@font-face').slice(1)) {
  const family = block.match(/font-family:\s*'([^']+)'/)?.[1];
  const weight = block.match(/font-weight:\s*(\d+)/)?.[1];
  const url = block.match(/url\((https:\/\/[^)]+\.woff2)\)/)?.[1];
  const range = block.match(/unicode-range:\s*([^;]+);/)?.[1] || '';
  // The latin subset is the one that carries basic ASCII.
  if (!family || !weight || !url || !/U\+0000-00FF/.test(range)) continue;
  faces.push({ family, weight, url, range: range.trim() });
}

if (faces.length !== 4)
  throw new Error(`expected 4 latin faces, got ${faces.length} — Google changed the response`);

mkdirSync(OUT, { recursive: true });
const decls = [];
for (const f of faces) {
  const slug = f.family.toLowerCase().replace(/[^a-z0-9]+/g, '-') + '-' + f.weight + '.woff2';
  const buf = Buffer.from(await (await fetch(f.url, { headers: { 'User-Agent': UA } })).arrayBuffer());
  writeFileSync(resolve(OUT, slug), buf);
  console.log(`  ${slug}  ${(buf.length / 1024).toFixed(1)} KB`);
  decls.push(`@font-face {
  font-family: '${f.family}';
  font-style: normal;
  font-weight: ${f.weight};
  font-display: swap;
  src: url('../fonts/${slug}') format('woff2');
  unicode-range: ${f.range};
}`);
}

writeFileSync(resolve(ROOT, 'css/fonts.css'),
  `/* Generated by tools/vendor-fonts.mjs. Do not hand-edit — re-run the tool.\n` +
  ` * Latin subsets only, served from fonts/ so the service worker can cache\n` +
  ` * them. Both families are SIL OFL 1.1; see fonts/OFL.txt. */\n\n` +
  decls.join('\n\n') + '\n', 'utf8');

console.log('wrote css/fonts.css with ' + faces.length + ' faces');
